name: Export Package

on:
  pull_request: {}
  push: { branches: [main] }
  
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  build:
    name: Build UnityPackage
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: CITestPackage/Library
          key: Library
          restore-keys: Library-
      
      # Build
      - name: Build .unitypackage
        uses: game-ci/unity-builder@v2
        with:
          projectPath: CITestPackage
          unityVersion: 2021.3.19f1
          buildMethod: PackageExporter.Export
      
      # Upload
      - name: Upload .unitypackage
        uses: actions/upload-artifact@v2
        with:
          name: Unity Package
          path: CITestPackage/package
          
